### ISSUE TITLE
使用metalibm生成不同精度版本

### ISSUE THREAD

**Issue by hiahiawei** [mathlib-cn/TGen#1]
作者你好，您这边论文中用到了metalibm做对比，但这一块网上资料比较少，能否提供一下使用matelibm生成的不同精度的超越函数实现代码，或者简要举例说明一下使用metalibm生成超越函数实现代码的命令。感谢~

**Comment by TimoTokki** [comment]
不好意思，看到消息比较晚。
metalibm的安装感觉是比较麻烦的。我之前参考的是[www.metalibm.org/index.html](http://www.metalibm.org/index.html)网站上的安装教程，刚看了下发现网页打不开了。
或许你可以参考https://github.com/metalibm/metalibm 进行安装。
如果有什么问题，欢迎继续交流

**Comment by TimoTokki** [comment]
基本上讲，metalibm是基于sollya实现的，或许你也可以参考https://www.sollya.org/ ，完成基础环境的安装

**Comment by hiahiawei** [comment]
好的，谢谢。现在已经装起来啦，嘿嘿嘿~
你的工作挺有意思的，也希望保持联系。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mathlib-cn/TGen"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月16日(星期四) 上午9:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mathlib-cn/TGen] 使用metalibm生成不同精度版本 (Issue #1)





 
基本上讲，metalibm是基于sollya实现的，或许你也可以参考https://www.sollya.org/，完成基础环境的安装

**Comment by TimoTokki** [comment]
🤝互相学习，有问题随时联系
